### PR TITLE
Describe Models

### PR DESCRIPTION
**Pull request by rkjain2006**
Module description added. DO we need to add fields with record creator and date in each model.

### CODE REVIEW

**Comment by rkjain2006** [comment]
Menu attached.

**Comment by rkjain2006** [comment]
Pl comment on two forms attached.

**Comment by rohitj** [comment]
I think you forgot to attach the file.

Rohit

**Comment by rkjain2006** [comment]
All main forms for production and sales.

**Comment by rkjain2006** [comment]
Forms with payment process.

**Comment by rkjain2006** [comment]
Menu and forms version-4.

**Comment by rkjain2006** [comment]
SD Module not implemented in master??

**Comment by rkjain2006** [comment]
MM migrated
SD in branch at header.
Pricing already in SD module.
Pl check forms.

**Pull request merged**
